#ifndef TALLER_TP_ITEM_SPAWN_MACROS_H
#define TALLER_TP_ITEM_SPAWN_MACROS_H

enum ItemSpawnId {
  GRENADE_SPAWN = 0x01,
  BANANA_SPAWN = 0x02,
  PEW_PEW_LASER_SPAWN = 0x03,
  LASER_RIFLE_SPAWN = 0x04,
  AK47_SPAWN = 0x05,
  DUEL_PISTOL_SPAWN = 0x06,
  COWBOY_PISTOL_SPAWN = 0x07,
  MAGNUM_SPAWN = 0x08,
  SHOTGUN_SPAWN = 0x09,
  SNIPER_SPAWN = 0x0A,
  HELMET_SPAWN = 0x0B,
  CHESTPLATE_SPAWN = 0x0C,
  NOTHING_SPAWN = 0x0D,
  EXPLOSION_SPAWN = 0x0E
};

#endif // TALLER_TP_ITEM_SPAWN_MACROS_H