#ifndef TALLER_TP_THROWABLE_MACROS_H
#define TALLER_TP_THROWABLE_MACROS_H

enum ThrowableId{
  THROWN_GRENADE_V2 = 0x00,
  THROWN_BANANA_V2 = 0x01,
  STEPPED_BANANA_V2 = 0x02
};

#endif // TALLER_TP_BULLET_MACROS_H