#ifndef TALLER_TP_WEAPON_MACROS_H
#define TALLER_TP_WEAPON_MACROS_H

enum WeaponId{
  NO_WEAPON = 0x00,
  GRENADE = 0x01,
  BANANA = 0x02,
  PEW_PEW_LASER = 0x03,
  LASER_RIFLE = 0x04,
  AK47 = 0x05,
  DUEL_PISTOL = 0x06,
  COWBOY_PISTOL = 0x07,
  MAGNUM = 0x08,
  SHOTGUN = 0x09,
  SNIPER = 0XA
};

#endif // TALLER_TP_WEAPON_MACROS_H