#ifndef TALLER_TP_CHEAT_MACROS_H
#define TALLER_TP_CHEAT_MACROS_H

enum CheatId{
  GET_GRENADE = 0x01,
  GET_BANANA = 0x02,
  GET_PEW_PEW_LASER = 0x03,
  GET_LASER_RIFLE = 0x04,
  GET_AK47 = 0x05,
  GET_DUEL_PISTOL = 0x06,
  GET_COWBOY_PISTOL = 0x07,
  GET_MAGNUM = 0x08,
  GET_SHOTGUN = 0x09,
  GET_SNIPER = 0x0A,
  GET_HELMET = 0x0B,
  GET_CHESTPLATE = 0x0C,
  WIN_INSTANTLY = 0x0D,
  KILL_ALL = 0x0E,
  THROW_EVERYTHING = 0x0F,
  NEXT_ROUND = 0x10,
  INFINITE_AMMO = 0x11
};

#endif // TALLER_TP_CHEAT_MACROS_H